# Generated by Django 5.0.4 on 2024-04-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_compensacao', models.IntegerField(unique=True)),
                ('nome_da_instituicao', models.CharField(max_length=200)),
            ],
        ),
    ]
