# Generated by Django 5.0.4 on 2024-04-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banco',
            table='bancos',
        ),
    ]
